### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by oscars810** [danielunderwood/swig-example#1]
Hello,

I'm trying to use cmake, swig and python with c++... And i don't kno how to run your example.
¿Can you explain me please?

**Comment by dfy888** [comment]
how to run your example?  can you help me ?

**Comment by danielunderwood** [comment]
Quite late on the response, but #2 has added some improved documentation and a docker file for setup. In short:

```shell
# Build libraries
mkdir build && cd build
cmake ..
make -j4
# Note that this currently installs in /usr/lib, which isn't ideal
make install
make install-python
# Go back to root dir to run
cd ..
python swig/python/test.sh
```

if you're running locally.
